#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number
news_create:
    path: /news
    methods: [POST]
    controller: App\Controller\NewsController::CreateNews
news_get:
    path: /news/{id}
    methods: [GET]
    controller: App\Controller\NewsController::GetNews
news_list:
    path: /news
    methods: [GET]
    controller: App\Controller\NewsController::ListNews
news_delete:
    path: /news/{id}
    methods: [DELETE]
    controller: App\Controller\NewsController::DeleteNews
news_update:
    path: /news/{id}
    methods: [PUT]
    controller: App\Controller\NewsController::UpdateNews

#  news_file:
# загружает маршруты из заданного файла маршрутизации, хранящегося в каком-то пакете
 #   resource: '/News_routing.yml'